# Generated by Django 4.2.2 on 2023-06-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_hide', models.BooleanField(default=False, verbose_name='Спрятан')),
                ('is_private', models.BooleanField(default=True, verbose_name='Приватний')),
                ('users', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='Учасники чата')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитан')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='message.group', verbose_name='Чат')),
            ],
        ),
    ]
