version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Gfhf_1_ljrc
      MYSQL_DATABASE: Social_db
      MYSQL_USER: John
      MYSQL_PASSWORD: Gfhf_2_ljrc
    volumes:
      - db_data:/var/lib/mysql
      

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: Social_db
      DB_USER: John
      DB_PASSWORD: Gfhf_2_ljrc


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  db_data:
  esdata: