# Generated by Django 4.2.2 on 2023-06-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tags',
            new_name='tag',
        ),
    ]
